name: Components
baseurl: /components

collections:
  pages:
    output: true
    permalink: /:name/

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - package.json
